version: 1.2
workflows:
 - name: ecoli_char
   subclass: WDL
   primaryDescriptorPath: /ecoli_char.wdl
   testParameterFiles:
    - empty.json
 - name: de_novo_assembly
   subclass: WDL
   primaryDescriptorPath: /de_novo_assembly.wdl
   testParameterFiles:
    - empty.json
 - name: BC_n_QC_PE
   subclass: WDL
   primaryDescriptorPath: /wf_bc_n_qc_pe.wdl
   testParameterFiles:
    - empty.json
