version: 1.2
workflows:
 - name: kSNP3
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ksnp3.wdl
   testParameterFiles:
    - empty.json
 - name: Apollo_Illumina_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_apollo_illumina_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Kleborate
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_kleborate.wdl
   testParameterFiles:
    - empty.json
 - name: SerotypeFinder
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_serotypefinder.wdl
   testParameterFiles:
    - empty.json
 - name: SeqSero2_FASTA
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_seqsero2_assembly_Kmode.wdl
   testParameterFiles:
    - empty.json
- name: SeqSero2_PE_Assembly
  subclass: WDL
  primaryDescriptorPath: /workflows/wf_seqsero2_PE_Amode.wdl
  testParameterFiles:
   - empty.json
   - name: SeqSero2_PE_Kmers
     subclass: WDL
     primaryDescriptorPath: /workflows/wf_seqsero2_PE_Kmode.wdl
     testParameterFiles:
      - empty.json
