version: 1.2
workflows:
 - name: cgMLST
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cgMLST_waphl.wdl
   testParameterFiles:
    - empty.json
 - name: create_cgMLST_schema
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_create_cgMLST_schema_WAPHL.wdl
   testParameterFiles:
    - empty.json
 - name: kSNP3
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ksnp3_WAPHL.wdl
   testParameterFiles:
    - empty.json
 - name: kSNP3_WAPHL
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ksnp3_WAPHL.wdl
   testParameterFiles:
    - empty.json
 - name: Pangenome_SNP_WAPHL
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_pangenome_snp_waphl.wdl
   testParameterFiles:
    - empty.json
#  - name: Prepare_References
#    subclass: WDL
#    primaryDescriptorPath: /workflows/wf_prepare_references.wdl
#    testParameterFiles:
#     - empty.json
 - name: WAPHL_report
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_waphl_report.wdl
   testParameterFiles:
    - empty.json

    - empty.json
 - name: TheiaProk_Illumina_PE_WAPHL
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_theiaprok_illumina_pe_WAPHL.wdl
   testParameterFiles:
    - empty.json
 - name: MashTree_FASTA
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mashtree_fasta.wdl
   testParameterFiles:
    - empty.json
 - name: NCBI-AMRFinderPlus
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_amrfinderplus.wdl
   testParameterFiles:
    - empty.json
 - name: Kraken2_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_kraken2_pe.wdl
   testParameterFiles:
    - empty.json
 - name: prep_bigdb_cgmlst
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_prep_cgmlst_WAPHL.wdl
   testParameterFiles:
    - empty.json
 - name: Recomb_aware_phylo_analysis_waphl
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_recombinant_aware_phylogenetic_analysis_waphl.wdl
   testParameterFiles:
    - empty.json
 - name: build_bacterial_consensus
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_build_bacterial_consensus.wdl
   testParameterFiles:
    - empty.json
 - name: recomb_clade_analysis
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_clade_analysis_WAPHL.wdl
   testParameterFiles:
    - empty.json
 - name: fetch_from_zip
   subclass: WDL
   primaryDescriptorPath: /workflows/fetch_from_zip.wdl
   testParameterFiles:
    - empty.json
 - name: WAPHL_bs_fetch
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_bs_fetch_WAPHL.wdl
   testParameterFiles:
    - empty.json